--Criando uma tabela com auto increment

-- Postgres

CREATE TABLE tb_identity(
	codigo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(50)
);

CREATE TABLE tb_identity(
	codigo INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nome VARCHAR(50)
);




--Populating the table
INSERT INTO tb_identity (nome)
VALUES ('Linha1'), ('Linha2');

-->Listar
SELECT * FROM tb_identity

-- Forçar erro passando o campo auto-increment

INSERT INTO tb_identity (codigo, nome)
VALUES (3, 'Linha3')

-->Listar
SELECT * FROM tb_identity

--DROP TABLE
DROP TABLE tb_identity